import Rocket from '../assets/static/the-hub-rocket.png';
import Rocket2x from '../assets/static/the-hub-rocket@2x.png';
import Balloon from '../assets/static/the-hub-balloons.png';
import Balloon2x from '../assets/static/the-hub-balloons@2x.png';
import Logo from '../assets/static/the-hub-logo-color.svg';
import LogoAlt from '../assets/static/the-hub-logo-alt.svg';
import HeroImage from '../assets/static/the-hub-hero-image.jpg';
import DrinkHero from '../assets/static/the-hub-drink-category-cover.jpg';
import DrinkSmall from '../assets/static/the-hub-drink-category-cover-small.jpg';
import PostCover from '../assets/uploads/examplPic4Post.jpg';
import leonaDavis from '../assets/uploads/leonaDavis.jpg';
import sampleImg1 from '../assets/uploads/singlePost_1.png';
import sampleImg2 from '../assets/uploads/singlePost_2.png';

export const LogoSmall = LogoAlt;
export const RocketImg = Rocket;
export const RocketGp = `${Rocket} 720w, ${Rocket2x} 360w`;
export const BalloonImg = Balloon;
export const BalloonGp = `${Balloon} 720w, ${Balloon2x} 360w`;
export const LogoRegular = Logo;
export const HeroImg = HeroImage;
export const DrinkCover = DrinkHero;
export const DrinkCoverSml = DrinkSmall;
export const PostCoverExample = PostCover;
export const AuthorImgExample = leonaDavis;
export const SampleImg1 = sampleImg1;
export const SampleImg2 = sampleImg2;
